business/business/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

business/orders/urls.py
from django.urls import path
from .views import CreateOrderView, user_products, OrderListView, OrderDeleteView

app_name = 'orders'

urlpatterns = [
    path('api/user-products/', user_products, name='user_products_api'),
    path('create_order/', CreateOrderView.as_view(), name='create_order'),
    path('all_orders/', OrderListView.as_view(), name='all_orders'),
    path('delete_order/<int:pk>', OrderDeleteView.as_view(), name='delete_order')
]

business/users/urls.py
from django.urls import path
from .views import RegistrationCreateView, UserUpdateView

app_name = "user"

urlpatterns = [
    path('registration/', RegistrationCreateView.as_view(), name='registration'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile')
]

business/orders/models.py
import datetime

from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models

from products.models import Product

User = get_user_model()


class Order(models.Model):
    buyer = models.CharField(max_length=30, verbose_name='Покупатель', blank=False, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    created = models.DateField(default=datetime.date.today, verbose_name='Дата покупки', blank=True, null=False)
    delivery = models.CharField(max_length=30, verbose_name='Способ доставки', blank=True,
                                help_text="Укажите способ доставки")

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ №{self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='product')
    product_name = models.CharField(max_length=40, verbose_name='Название товара', blank=False, null=False, default='')
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0.01)], default=0.01,
                                verbose_name='Цена')
    quantity = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0.01)])

    class Meta:
        verbose_name = 'Позиция в заказе'
        verbose_name_plural = 'Позиции в заказах'

    def __str__(self):
        return f'Позициця в заказе {self.order.id}'

business/orders/forms.py
from django import forms
from .models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['buyer', 'delivery', 'created']
        widgets = {
            'created': forms.DateInput(attrs={'type': 'date'}),
        }


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product', 'quantity', 'price']

business/orders/views.py
import datetime
from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch, Sum, F
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from .forms import OrderForm
from .models import OrderItem, Order
from .util import check_products, check_date
from products.models import Product

import json


@login_required
def user_products(request):
    user_product = Product.objects.filter(user=request.user).values('id', 'title', 'selling_price', 'amount')
    return JsonResponse(list(user_product), safe=False)


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'orders/all_orders.html'  # Шаблон для отображения
    context_object_name = 'orders'  # Имя переменной в шаблоне
    paginate_by = 10

    def get_queryset(self):
        order_items = OrderItem.objects.select_related('product')
        orders = (Order.objects.prefetch_related(Prefetch('order', queryset=order_items))
                  .filter(user=self.request.user).order_by('-created'))

        for order in orders:
            order.total_price = sum(
                item.price * item.quantity for item in order.order.all()
            )
        return orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        revenue = \
            (OrderItem.objects.filter(order__user=self.request.user).annotate(total_price=F('price') * F('quantity'))
             .aggregate(total_revenue=Sum('total_price')))['total_revenue'] or 0
        context['revenue'] = revenue
        return context


class OrderDeleteView(LoginRequiredMixin, View):
    model = Order
    template_name = 'orders/delete_order.html'
    success_url = reverse_lazy('orders:all_orders')

    def get(self, request, pk):
        order = get_object_or_404(Order, pk=pk, user=self.request.user)
        return render(request, 'orders/delete_order.html', {'order': order})

    def post(self, request, pk):
        order = get_object_or_404(Order, pk=pk, user=self.request.user)
        return_products = request.POST.get('return_products') == 'on'
        if return_products:
            for item in order.order.all():
                try:
                    product = item.product
                    if product is None:
                        continue
                    product.amount += item.quantity
                    product.save()
                except Product.DoesNotExist:
                    pass
        order.delete()
        return redirect('orders:all_orders')


class CreateOrderView(LoginRequiredMixin, View):
    def get(self, request):
        form = OrderForm()
        return render(request, 'orders/create_order.html', {'form': form})

    def post(self, request):
        errors_log = set()

        data = json.loads(request.body)
        form_data = request.POST.copy()
        form_data['buyer'] = data.get('buyer')
        form_data['delivery'] = data.get('delivery')
        form_data['created'] = datetime.date.today()
        if check_date(data.get('created')):
            form_data['created'] = data.get('created')

        form = OrderForm(form_data)
        if check_products(data, request.user.id, errors_log) and form.is_valid():
            order = form.save(commit=False)
            order.user = request.user

            products_to_save = dict()
            for product in data['products']:
                product_id = product.get('product_id')
                price = float(product.get('price'))
                quantity = float(product.get('quantity'))

                product_obj = Product.objects.get(id=product_id, user=request.user)
                if product_id in products_to_save:
                    products_to_save[product_id]['quantity'] += quantity
                else:
                    products_to_save[product_id] = {'product': product_obj, 'quantity': quantity, 'price': price,
                                                    'product_name': product_obj.title}
            order.save()
            for product in products_to_save:
                data = products_to_save[product]
                product_obj = data['product']
                product_obj.amount -= Decimal(data['quantity'])
                product_obj.save()
                OrderItem.objects.create(order=order, product=data['product'], quantity=data['quantity'],
                                         price=data['price'], product_name=data['product_name'])
            return redirect('homepage:index')
        return JsonResponse({'error': ' '.join(list(errors_log))}, status=400)

business/templates/orders/all_orders.html
{% extends "base.html" %}

{% block title %}Список заказов{% endblock %}

{% block content %}
<h3>Ваша общая выручка: {{ revenue }}</h3>
<p>Здесь вы можете управлять своими продажами. </p>
<a href="{% url 'orders:create_order' %}">Создать заказ</a>
<hr>
{% if orders %}
    <table class="orders-table">
        <thead>
            <tr>
                <th>Номер заказа</th>
                <th>Покупатель</th>
                <th>Способ доставки</th>
                <th>Дата создания</th>
                <th>Детали заказа</th>
                <th>Выручка</th>
                <th>Удалить</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.buyer }}</td>
            <td>{{ order.delivery }}</td>
            <td>{{ order.created|date:"d.m.Y" }}</td>
            <td>
                <ul>
                    {% for item in order.order.all %}
                    <li class="order_list">
                        {{ item.product_name }} - {{ item.quantity|floatformat:"g" }} x {{ item.price|floatformat:"g" }} руб.
                    </li>
                    {% endfor %}
                </ul>
            </td>
            <td> {{ order.total_price|floatformat:"g" }} руб </td>
            <td><a href="{% url 'orders:delete_order' order.id %}">Удалить заказ</a></td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    {% include 'includes/paginator.html' %}
{% else %}
    <p>У вас пока нет заказов.</p>
{% endif %}
{% endblock %}

business/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}

{% block title %}Создание заказа{% endblock %}

{% block content %}
<h1>Создание заказа</h1>
<p class="plain_text">При создании заказа вы можете добавить множество своих товаров. Но следите, чтобы оставшееся количество товара
    не превышало его клочество в заказе, иначе он не будет создан.</p>
<form id="order-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="products-list"></div>
    <button type="button" id="add-product-button">Добавить товар</button>
    <button type="submit">Создать заказ</button>
</form>
<script>
    const api_url = "{% url 'orders:user_products_api' %}";
    const send_data = "{% url 'orders:create_order' %}";
    const redirect_url = "{% url 'orders:all_orders' %}";
</script>
<script src="{% static 'js/created_order.js' %}"></script>
{% endblock %}

business/templates/orders/delete_order.html
{% extends "base.html" %}
{% block title %}Удаление{% endblock %}

{% block content %}
  <p>Вы уверены, что хотите удалить заказ №{{ order.id }}? Это действие необратимо.</p>
  <form method="post">
    {% csrf_token %}
    <p>
        <label>
            <input type="checkbox" name="return_products" checked>
            Вернуть товары из заказа на склад
        </label>
    </p>
    <input type="submit" value="Удалить">
  </form>
{% endblock %}