business/business/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

business/users/urls.py
from django.urls import path
from .views import RegistrationCreateView, UserUpdateView

app_name = "user"

urlpatterns = [
    path('registration/', RegistrationCreateView.as_view(), name='registration'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile')
]

business/templates/includes/footer.html
<footer>
  <p class="footer_p">Курсовая работа. Носов Д.В. ИКБО-20-22</p>
</footer>

business/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <div
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'homepage:index' %} active {% endif %}"
              href="{% url 'homepage:index' %}"
              >
              Главная
            </a>
          </li>

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link {% if view_name == 'categories:all_categories' %} active {% endif %}"
                href="{% url 'categories:all_categories' %}"
                >
                Категории
              </a>
            </li>
          <li class="nav-item">
              <a
                class="nav-link {% if view_name == 'products:heap_products' %} active {% endif %}"
                href="{% url 'products:heap_products' 'title' %}"
                >
                Все товары
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if view_name == 'orders:all_orders' %} active {% endif %}"
                href="{% url 'orders:all_orders' %}"
                >
                Заказы
              </a>
            </li>
          </ul>
          <div class="text_login">
            <span style="margin: auto 0;">Привет,  <b>{{ user.first_name }}</b></span>
              <a
                class="nav-link"
                href="{% url 'user:profile' user.id %}"
                >
                Профиль
              </a>
              <form method="post" action="{% url 'logout' %}" style="margin: auto 0;">
                  {% csrf_token %}
                  <button style=" color: #0d6efd; background-color: transparent; border:none;" type="submit">Logout</button>
              </form>
          {% else %}
              <a class="nav-link {% if view_name == 'login' %}active{% endif %}" href="{% url 'login' %}">Войти</a>
          {% endif %}
        </div>
        {% endwith %}
      </div>
      <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'img/logo-2.png' %}" height="50" class="d-inline-block align-top" alt="">
      </a>
    </div>
  </nav>
</header>

business/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination">
      <!-- Если существует предыдущая страница
           (если мы не на первой странице)
           рисуем кнопку "Первая страница"... -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <!-- ...и кнопку "Предыдущая" -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      <!-- Перебираем в цикле все номера страниц -->
      {% for i in page_obj.paginator.page_range %}
        <!-- Если номер страницы совпадает с i... -->
        {% if page_obj.number == i %}
          <!-- ..."подсвечиваем" кнопку: ставим класс "active"
               и делаем не ссылку, а span (просто текстовый блок) -->
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <!-- Остальные кнопки отрисовываем без подсветки, со ссылками -->
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <!-- Если существует следующая страница
           (если мы не на последней странице)
           рисуем кнопку "Следующая"... -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <!-- ...и кнопку "Последняя" -->
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}