business/business/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

business/categories/urls.py
from django.urls import path
from .views import CreateCategoryView, CategoryListView, UpdateCategoryView, DeleteCategoryView

app_name = "categories"

urlpatterns = [
    path('', CategoryListView.as_view(), name="all_categories"),
    path('create/', CreateCategoryView.as_view(), name="create_category"),
    path('<int:pk>/update/', UpdateCategoryView.as_view(), name="update_category"),
    path('<int:pk>/delete/', DeleteCategoryView.as_view(), name="delete_category")
]

business/products/urls.py
from django.urls import path
from .views import (ProductListView, CreateProductView, UpdateProductView, DeleteProductView,
                    HeapProductListView)

app_name = 'products'

urlpatterns = [
    path('<int:category_id>/all_products', ProductListView.as_view(), name='all_products'),
    path('<int:category_id>/create_product', CreateProductView.as_view(), name='create_product'),
    path('<int:category_id>/update_product/<int:pk>', UpdateProductView.as_view(), name='update_product'),
    path('<int:category_id>/delete_product/<int:pk>', DeleteProductView.as_view(), name='delete_product'),
    path('heap_products/<slug:sort>', HeapProductListView.as_view(), name='heap_products')
]

business/users/urls.py
from django.urls import path
from .views import RegistrationCreateView, UserUpdateView

app_name = "user"

urlpatterns = [
    path('registration/', RegistrationCreateView.as_view(), name='registration'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile')
]

business/categories/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Category(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,  # удаление пользователя удалит категории
                             related_name='categories',
                             verbose_name='Пользователь',
                             db_column="user_id")
    title = models.CharField(max_length=30, blank=False, null=False, verbose_name='Название')
    description = models.TextField(blank=False, null=False, verbose_name='Описание')

    class Meta:
        unique_together = ('user', 'title')
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ('-title', )

    def __str__(self):
        return self.title

business/categories/forms.py
from django import forms

from .models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5, 'cols': 10})
        }

business/categories/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from .forms import CategoryForm
from .models import Category

REDIRECT_TO = 'categories:all_categories'


class CategoryListView(LoginRequiredMixin, ListView):
    """Страница со всеми категориями"""
    model = Category
    template_name = 'categories/all_categories.html'
    paginate_by = 4

    def get_queryset(self):
        queryset = Category.objects.filter(user=self.request.user).annotate(
            total_sales=Sum('products__product__quantity'),
            total_revenue=Sum(F('products__product__quantity') * F('products__product__price'))
        ).order_by('title')
        return queryset


class UpdateCategoryView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'categories/update_category.html'
    success_url = reverse_lazy(REDIRECT_TO)

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user)


class DeleteCategoryView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = 'categories/delete_category.html'
    success_url = reverse_lazy(REDIRECT_TO)

    def get_queryset(self):
        categories = Category.objects.filter(user=self.request.user)

        return categories


class CreateCategoryView(LoginRequiredMixin, CreateView):
    """
    Страница создания категории
    """
    model = Category
    form_class = CategoryForm
    template_name = 'categories/create_category.html'
    success_url = reverse_lazy(REDIRECT_TO)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

business/templates/categories/all_categories.html
{% extends "base.html" %}

{% block title %} Категории {% endblock %}
{% block content %}
  <p class="plain_text">Это страница с вашими категориями товаров. Здесь вы можете объединять товары в одну категории
  и следить за статистикой продаж. Перед тем как создать товар, создайте категорию.</p>
  <a href="{% url 'categories:create_category' %}">Создать категорию</a>
  <hr>
  {% if page_obj  %}
  <div class="categories">
    {% for category in page_obj  %}
      <div class="category">
        <b>{{ category.title }}</b> <span>- {{ category.description }}</span>
        <p>Кол-во продаж: {{ category.total_sales|default:0 }}</p>
        <p>Выручка {{ category.total_revenue|default:0 }}</p>
        <a href="{% url 'categories:update_category' category.id %}">Обновить категорию</a> |
        <a href="{% url 'categories:delete_category' category.id %}">Удалить категорию</a> |
        <a href="{% url 'products:all_products' category.id %}">Товары из категории</a>
      </div>
    {% endfor %}
  </div>
  {%  include 'includes/paginator.html' %}
  {% else %}
    <p>К сожалению, у вас пока нет категорий, но вы можете их создать</p>
  {% endif %}
{% endblock %}

business/templates/categories/create_category.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Создание категории {% endblock %}
{% block content %}
  <h2>Создание категории</h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Создать" %}
  </form>
{% endblock %}

business/templates/categories/delete_category.html
{% extends "base.html" %}

{% block title %}Удаление{% endblock %}

{% block content %}
  <p>Вы уверены, что хотите удалить категорию "{{ category.title }}"
    с описанием "{{ category.description|truncatewords:10 }}"?</p>
  <p>Категорию невозможно вернуть, а вместе с ней будут удалены все её товары. </p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
{% endblock %}

business/templates/categories/update_category.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Редактирование категории{% endblock %}

{% block content %}
  <h2>Редактировать категорию</h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Сохранить изменения" %}
  </form>
  <a href="{% url 'categories:all_categories' %}">Назад</a>
{% endblock %}