business/business/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('user/', include('users.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

business/categories/urls.py
from django.urls import path
from .views import CreateCategoryView, CategoryListView, UpdateCategoryView, DeleteCategoryView

app_name = "categories"

urlpatterns = [
    path('', CategoryListView.as_view(), name="all_categories"),
    path('create/', CreateCategoryView.as_view(), name="create_category"),
    path('<int:pk>/update/', UpdateCategoryView.as_view(), name="update_category"),
    path('<int:pk>/delete/', DeleteCategoryView.as_view(), name="delete_category")
]

business/products/urls.py
from django.urls import path
from .views import (ProductListView, CreateProductView, UpdateProductView, DeleteProductView,
                    HeapProductListView)

app_name = 'products'

urlpatterns = [
    path('<int:category_id>/all_products', ProductListView.as_view(), name='all_products'),
    path('<int:category_id>/create_product', CreateProductView.as_view(), name='create_product'),
    path('<int:category_id>/update_product/<int:pk>', UpdateProductView.as_view(), name='update_product'),
    path('<int:category_id>/delete_product/<int:pk>', DeleteProductView.as_view(), name='delete_product'),
    path('heap_products/<slug:sort>', HeapProductListView.as_view(), name='heap_products')
]

business/users/urls.py
from django.urls import path
from .views import RegistrationCreateView, UserUpdateView

app_name = "user"

urlpatterns = [
    path('registration/', RegistrationCreateView.as_view(), name='registration'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile')
]

business/products/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models

from categories.models import Category

User = get_user_model()


class Product(models.Model):
    title = models.CharField(max_length=20, verbose_name='Название товара',
                             blank=False, null=False)
    description = models.TextField(verbose_name='Описание товара')
    selling_price = models.DecimalField(max_digits=10, decimal_places=2,
                                        validators=[MinValueValidator(0.01)],
                                        verbose_name='Цена продажи',
                                        blank=False, null=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2,
                                 verbose_name='Кол-во', validators=[MinValueValidator(0)],
                                 blank=False, null=False, help_text="Кол-во товара в наличии")
    measure_unit = models.CharField(max_length=15, verbose_name='Единицы измерения', blank=False,
                                    null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')

    class Meta:
        unique_together = ('title', 'user', 'category')
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ('category', 'title',)

    def __str__(self):
        return self.title

business/products/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'description', 'selling_price', 'amount', 'measure_unit')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5, 'cols': 10}),
        }

business/products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from .models import Product
from .forms import ProductForm
from categories.models import Category


REDIRECT_TO = 'products:all_products'


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    form_class = ProductForm
    template_name = 'products/all_products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        context['category'] = Category.objects.get(pk=category_id, user=self.request.user)
        context['products'] = Product.objects.filter(user=self.request.user,
                                                     category=category_id)
        return context


class CreateProductView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/create_product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        category = Category.objects.get(pk=category_id,
                                        user=self.request.user)
        context['category'] = category
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user  # Привязываем товар к текущему пользователю
        category_id = self.kwargs.get('category_id')
        category = get_object_or_404(Category, pk=category_id, user=self.request.user)
        form.instance.category = category
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(REDIRECT_TO, kwargs={'category_id': self.kwargs.get('category_id')})


class UpdateProductView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/update_product.html'

    def get_object(self, queryset=None):
        category_id = self.kwargs.get('category_id')
        return get_object_or_404(
            Product,
            pk=self.kwargs.get('pk'),
            user=self.request.user,
            category_id=category_id
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_id'] = self.kwargs.get('category_id')
        return context

    def get_success_url(self):
        return reverse_lazy(REDIRECT_TO, kwargs={'category_id': self.kwargs.get('category_id')})


class DeleteProductView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'products/delete_product.html'

    def get_object(self, queryset=None):
        category_id = self.kwargs.get('category_id')
        return get_object_or_404(
            Product,
            pk=self.kwargs.get('pk'),
            user=self.request.user,
            category_id=category_id
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_id'] = self.kwargs.get('category_id')
        return context

    def get_success_url(self):
        return reverse_lazy(REDIRECT_TO, kwargs={'category_id': self.kwargs.get('category_id')})


class HeapProductListView(LoginRequiredMixin, ListView):
    model = Product
    form_class = ProductForm
    template_name = 'products/heap_products.html'
    context_object_name = 'products'
    paginate_by = 20

    def get_queryset(self):
        sort_type = self.request.GET.get('sort', 'title')
        if sort_type not in ['title', '-title', 'selling_price', '-selling_price',
                             'total_sales', '-total_sales', 'total_revenue', '-total_revenue']:
            sort_type = 'title'

        products = Product.objects.filter(user=self.request.user)

        products = products.annotate(
            total_sales=Sum('product__quantity'),
            total_revenue=Sum(F('product__quantity') * F('product__price'))
        ).select_related('category').order_by(sort_type)

        return products

business/templates/products/all_products.html
{% extends "base.html" %}

{% block title %}Товары категории {% endblock %}

{% block content %}
  <h1>Товары в категории "{{ category.title }}"</h1>
  <p>Описание категории: {{category.description}}</p>
  <a href="{% url 'products:create_product' category.id %}">Создать товар</a>
  <hr>
  {% if products %}
      {% for product in products %}
        <div class="product">
          <p>{{ product.title }} - {{ product.description }}. Цена {{ product.selling_price }}</p>
          <p>{% if product.amount > 0 %}
          Осталось {{ product.amount|floatformat:"g" }} {{ product.measure_unit }}
          {% else %} Товар закончился :( {% endif %}</p>
          <a href="{% url 'products:update_product' category.id product.id %}">Изменить товар</a> |
          <a href="{% url 'products:delete_product' category.id product.id %}">Удалить товар</a>
        </div>
      {% endfor %}
  {% else %}
    <p>В этой категории нет товаров.</p>
  {% endif %}
  <a href="{% url 'categories:all_categories' %}">Назад</a>
{% endblock %}

business/templates/products/create_product.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Создание товара {% endblock %}
{% block content %}
  <h2>Вы создаёте товар, относящийся к категории "{{ category.title }}"</h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Создать" %}
  </form>
  <a href="{% url 'products:all_products' category.id %}">Назад</a>
{% endblock %}

business/templates/products/delete_product.html
{% extends "base.html" %}

{% block title %}Удаление{% endblock %}

{% block content %}
  <p>Вы уверены, что хотите удалить товар "{{ product.title }}"
    с описанием "{{ product.description|truncatewords:10 }}"?</p>
  {% if product.amount > 0 %}
    <p>У вас осталось ещё {{ product.amount|floatformat:"g" }} {{ product.measure_unit }}</p>
  {% else %}
    <p>Такого товара у вас больше не осталось</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
  <a href="{% url 'products:all_products' category_id %}">Назад</a>
{% endblock %}

business/templates/products/heap_products.html
{% extends "base.html" %}

{% block title %}Все товары{% endblock %}
{% block content %}
  <p>
    На этой странице вы можете увидеть статистику по всем своим товарам и сравнить их. Редактировать товары
    можно через категории
  </p>
  <form method="get" action="{% url 'products:heap_products' 'sort' %}">
    <label for="sort">Сортировать по:</label>
    <select name="sort" id="sort">
        <option value="title" {% if request.GET.sort == 'title' %}selected{% endif %}>Название А-Я</option>
        <option value="-title" {% if request.GET.sort == '-title' %}selected{% endif %}>Название Я-А</option>

        <option value="selling_price" {% if request.GET.sort == 'selling_price' %}selected{% endif %}>Цена (сначала дешевле)</option>
        <option value="-selling_price" {% if request.GET.sort == '-selling_price' %}selected{% endif %}>Цена (сначала дороже)</option>

        <option value="total_sales" {% if request.GET.sort == 'total_sales' %}selected{% endif %}>Количество продаж (сначала меньше)</option>
        <option value="-total_sales" {% if request.GET.sort == '-total_sales' %}selected{% endif %}>Количество продаж (сначала больше)</option>

        <option value="total_revenue" {% if request.GET.sort == 'total_revenue' %}selected{% endif %}>Сумма продаж (сначала меньше)</option>
        <option value="-total_revenue" {% if request.GET.sort == '-total_revenue' %}selected{% endif %}>Сумма продаж (сначала больше)</option>
    </select>
    <input type="submit" value="Отсортировать">
  </form>
<hr>


  {% for product in products %}
    <div class="product">
      <p>{{ product.title }}: {{ product.description|truncatewords:5 }} | Категория: <span><a href="{% url 'products:all_products' product.category.id %}">{{ product.category.title }}</a></span> </p>
      <p>Осталось: {{ product.amount }} {{ product.measure_unit }}, цена: {{ product.selling_price }} руб. Кол-во продаж:
          {{ product.total_sales|default:0 }}, выручка: {{ product.total_revenue|default:0 }} руб</p>
    </div>
  {% endfor %}


  {% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1&sort={{ request.GET.sort }}">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}&sort={{ request.GET.sort }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}&sort={{ request.GET.sort }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}&sort={{ request.GET.sort }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&sort={{ request.GET.sort }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}

{% endblock %}

business/templates/products/update_product.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Обновление товара {% endblock %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Создать" %}
  </form>
  <a href="{% url 'products:all_products' category_id %}">Назад</a>
{% endblock %}